### PR TITLE
Use channel flag rather than list of chan

### PR DESCRIPTION
**Pull request by crazycatdevs**
- removed the Channels(Allow) variable
- added youtube channel flag
Youtube link can be enable by using .chanset #channel +youtube, or .chanset * +youtube to activate on all channels. Same to deactivate

### CODE REVIEW

**Comment by ZarTek-Creole** [comment]
Thank you for your PR suggestion. However, it requires prior discussion. What advantages or disadvantages do the flags bring rather than a list of configurable channels in the same places as the other options of the TCL-Youtube-Link script?

**Comment by crazycatdevs** [comment]
hmmm, 

- not have to reload the script after having change the list ?
- seeing if it's enabled with .chaninfo ?
- giving someone else (chanowner) the right to add the script in its channel ?

**Comment by ZarTek-Creole** [comment]
I grant you these arguments as positive to your system. The two could coexist: If the channel is in the whitelist OR if the channel has the flag then the script works on the channel. It leaves the simplicity of one and the advantages of the other, a win win

**Comment by ZarTek-Creole** [comment]
Done in f3a78e1b48975337556786b059bf4221ae4c4c51, Thank you

**Pull request closed without merging**
